sudo: required

services:
  - docker

before_install:
  - docker build -t jasl8r/cobbler .
  - docker build -f Dockerfile-cobblerd -t jasl8r/cobblerd .
  - docker build -f Dockerfile-tftpd -t jasl8r/tftpd .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jasl8r/cobblerd;
    docker push jasl8r/tftpd;
    fi
