FROM jasl8r/cobbler
MAINTAINER jasl8r@alum.wpi.edu

RUN pip install tornado

EXPOSE 69/udp

CMD ["dockerize", \
     "-stdout", "/var/log/cobbler/cobbler.log", \
     "python", "/usr/local/sbin/tftpd.py", "--user", "root", "-v"]
